from typing import Callable, Union, List, Dict
from pathlib import Path

import plotly.express as px
import dash_html_components as html
import dash_core_components as dcc
import webviz_core_components as wcc
from webviz_subsurface._models import EnsembleTableModelSet


def data_selectors_view(
    get_uuid: Callable,
    ensemble_names=List[str],
    data_column_names=List[str],
    parameter_names=List[str],
) -> html.Div:
    return html.Div(
        className="framed",
        style={"fontSize": "0.8em"},
        children=[
            html.H5("Data selectors"),
            dropdown_for_plotly_data(
                uuid=get_uuid("data_selectors"),
                source="table",
                data_attribute="ensemble",
                title="Ensemble",
                options=[{"label": col, "value": col} for col in ensemble_names],
                value=[ensemble_names[0]],
                multi=True,
            ),
            dropdown_for_plotly_data(
                uuid=get_uuid("plotly_data"),
                source="table",
                data_attribute="x",
                title="X-value",
                options=[{"label": col, "value": col} for col in data_column_names],
                value=data_column_names[0],
            ),
            dropdown_for_plotly_data(
                uuid=get_uuid("plotly_data"),
                source="table",
                data_attribute="y",
                title="Y-value",
                options=[{"label": col, "value": col} for col in data_column_names],
                value=data_column_names[-1],
            ),
            # dropdown_for_plotly_data(
            #     uuid=get_uuid("plotly_data"),
            #     source="parameters",
            #     data_attribute="color",
            #     title="Color",
            #     options=[{"label": col, "value": col} for col in parameter_names],
            #     value=parameter_names[0],
            #     clearable=True,
            # ),
            color_scale_dropdown(
                uuid=get_uuid("colorscale"),
                title="Colorscale",
                options=[
                    {"label": col, "value": col}
                    for col in [
                        "Plotly3",
                        "Viridis",
                        "Cividis",
                        "Inferno",
                        "Magma",
                        "Plasma",
                        "Turbo",
                        "Blackbody",
                        "Bluered",
                        "Electric",
                        "Hot",
                        "Jet",
                        "Rainbow",
                        "Blues",
                        "BuGn",
                        "BuPu",
                        "GnBu",
                        "Greens",
                        "Greys",
                        "OrRd",
                        "Oranges",
                        "PuBu",
                        "PuBuGn",
                        "PuRd",
                        "Purples",
                        "RdBu",
                        "RdPu",
                        "Reds",
                        "YlGn",
                        "YlGnBu",
                        "YlOrBr",
                        "YlOrRd",
                        "turbid",
                        "thermal",
                        "haline",
                        "solar",
                        "ice",
                        "gray",
                        "deep",
                        "dense",
                        "algae",
                        "matter",
                        "speed",
                        "amp",
                        "tempo",
                        "Burg",
                        "Burgyl",
                        "Redor",
                        "Oryel",
                        "Peach",
                        "Pinkyl",
                        "Mint",
                        "Blugrn",
                        "Darkmint",
                        "Emrld",
                        "Aggrnyl",
                        "Bluyl",
                        "Teal",
                        "Tealgrn",
                        "Purp",
                        "Purpor",
                        "Sunset",
                        "Magenta",
                        "Sunsetdark",
                        "Agsunset",
                        "Brwnyl",
                        "Plotly3_r",
                        "Viridis_r",
                        "Cividis_r",
                        "Inferno_r",
                        "Magma_r",
                        "Plasma_r",
                        "Turbo_r",
                        "Blackbody_r",
                        "Bluered_r",
                        "Electric_r",
                        "Hot_r",
                        "Jet_r",
                        "Rainbow_r",
                        "Blues_r",
                        "BuGn_r",
                        "BuPu_r",
                        "GnBu_r",
                        "Greens_r",
                        "Greys_r",
                        "OrRd_r",
                        "Oranges_r",
                        "PuBu_r",
                        "PuBuGn_r",
                        "PuRd_r",
                        "Purples_r",
                        "RdBu_r",
                        "RdPu_r",
                        "Reds_r",
                        "YlGn_r",
                        "YlGnBu_r",
                        "YlOrBr_r",
                        "YlOrRd_r",
                        "turbid_r",
                        "thermal_r",
                        "haline_r",
                        "solar_r",
                        "ice_r",
                        "gray_r",
                        "deep_r",
                        "dense_r",
                        "algae_r",
                        "matter_r",
                        "speed_r",
                        "amp_r",
                        "tempo_r",
                        "Burg_r",
                        "Burgyl_r",
                        "Redor_r",
                        "Oryel_r",
                        "Peach_r",
                        "Pinkyl_r",
                        "Mint_r",
                        "Blugrn_r",
                        "Darkmint_r",
                        "Emrld_r",
                        "Aggrnyl_r",
                        "Bluyl_r",
                        "Teal_r",
                        "Tealgrn_r",
                        "Purp_r",
                        "Purpor_r",
                        "Sunset_r",
                        "Magenta_r",
                        "Sunsetdark_r",
                        "Agsunset_r",
                        "Brwnyl_r",
                    ]
                ],
                value="Rainbow",
                clearable=True,
            ),
        ],
    )


def dropdown_for_plotly_data(
    uuid: str,
    source: str,
    data_attribute: str,
    title: str,
    options: List[Dict],
    value: Union[List, str] = None,
    flex: int = 1,
    placeholder: str = "Select...",
    multi=False,
    clearable=False,
) -> html.Div:
    return html.Div(
        style={"flex": flex},
        children=[
            html.Label(title),
            dcc.Dropdown(
                id={"id": uuid, "data_attribute": data_attribute, "source": source},
                options=options,
                value=value,
                clearable=clearable,
                placeholder=placeholder,
                multi=multi,
            ),
        ],
    )


def color_scale_dropdown(
    uuid: str,
    title: str,
    options: List[Dict],
    value: Union[List, str] = None,
    flex: int = 1,
    placeholder: str = "Select...",
    multi=False,
    clearable=False,
) -> html.Div:
    return html.Div(
        style={"flex": flex},
        children=[
            html.Label(title),
            dcc.Dropdown(
                id=uuid,
                options=options,
                value=value,
                clearable=clearable,
                placeholder=placeholder,
                multi=multi,
            ),
        ],
    )